package com.misset.omt.qualitygate.model.scalars;

import org.yaml.snakeyaml.nodes.Node;

/**
 * Specific extension of string that is used to declare the prefix used for the instances of the classes
 * generated by parsing the !Ontology modelitem. The prefix must be declared in accessible context of the !Ontology
 * which currently is the document root / prefixes location.
 */
public class OntologyPrefixStringElement extends StringElement {
    public static final String PREFIX = "prefix";

    public OntologyPrefixStringElement(Node node) {
        super(node);
    }
}
